[build]
  command = "npm run build"
  publish = "/"
  functions = "functions"
  targetPort = 3000


[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 3000

[build.environment]
  NODE_VERSION = "18.17.0"  # Specify the Node.js version you're using

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
